In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('sample_data.csv')
data.head()

Region   Age    Income Online Shopper
0  Brazil  38.0   83572.0             No
1     USA  26.0  106573.0             No
2  Brazil   NaN       NaN            Yes
3     USA  20.0  107675.0             No
4   India   NaN       NaN             No

In [16]:
X = data.iloc[: , :-1].values

In [19]:
y = data.iloc[: , -1].values

In [21]:
from sklearn.impute import SimpleImputer

In [24]:
si = SimpleImputer(missing_values=np.nan , strategy='mean')
si.fit(X[: , 1:])
X[: , 1:] = si.transform(X[: , 1:])

In [27]:
X

array([['Brazil', 38.0, 83572.0],
       ['USA', 26.0, 106573.0],
       ['Brazil', 42.425, 84411.45],
       ['USA', 20.0, 107675.0],
       ['India', 42.425, 84411.45],
       ['India', 42.425, 84411.45],
       ['Brazil', 42.425, 84411.45],
       ['Brazil', 21.0, 88417.0],
       ['USA', 41.0, 95610.0],
       ['Brazil', 30.0, 93070.0],
       ['Brazil', 42.425, 84411.45],
       ['USA', 42.0, 99195.0],
       ['India', 26.0, 72067.0],
       ['Brazil', 57.0, 52503.0],
       ['USA', 38.0, 111125.0],
       ['USA', 68.0, 113726.0],
       ['USA', 54.0, 67414.0],
       ['USA', 27.0, 66479.0],
       ['Brazil', 46.0, 43105.0],
       ['USA', 42.425, 84411.45],
       ['India', 42.425, 84411.45],
       ['USA', 58.0, 72774.0],
       ['USA', 25.0, 98620.0],
       ['India', 30.0, 43624.0],
       ['USA', 42.425, 84411.45],
       ['India', 36.0, 89203.0],
       ['USA', 42.425, 84411.45],
       ['USA', 58.0, 94680.0],
       ['India', 68.0, 82844.0],
       ['Brazil', 58.0, 118065.0

In [26]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()
X[: , 0] = le.fit_transform(X[: , 0])

In [29]:
X

array([[0, 38.0, 83572.0],
       [2, 26.0, 106573.0],
       [0, 42.425, 84411.45],
       [2, 20.0, 107675.0],
       [1, 42.425, 84411.45],
       [1, 42.425, 84411.45],
       [0, 42.425, 84411.45],
       [0, 21.0, 88417.0],
       [2, 41.0, 95610.0],
       [0, 30.0, 93070.0],
       [0, 42.425, 84411.45],
       [2, 42.0, 99195.0],
       [1, 26.0, 72067.0],
       [0, 57.0, 52503.0],
       [2, 38.0, 111125.0],
       [2, 68.0, 113726.0],
       [2, 54.0, 67414.0],
       [2, 27.0, 66479.0],
       [0, 46.0, 43105.0],
       [2, 42.425, 84411.45],
       [1, 42.425, 84411.45],
       [2, 58.0, 72774.0],
       [2, 25.0, 98620.0],
       [1, 30.0, 43624.0],
       [2, 42.425, 84411.45],
       [1, 36.0, 89203.0],
       [2, 42.425, 84411.45],
       [2, 58.0, 94680.0],
       [1, 68.0, 82844.0],
       [0, 58.0, 118065.0],
       [0, 56.0, 54920.0],
       [0, 49.0, 118342.0],
       [0, 39.0, 61169.0],
       [2, 63.0, 51535.0],
       [0, 69.0, 110862.0],
       [2, 42.425, 84

In [30]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [33]:
ct = ColumnTransformer([('country' , OneHotEncoder() , [0])] , remainder='passthrough')
X = ct.fit_transform(X)
X

array([[0.0, 1.0, 0.0, 0.0, 38.0, 83572.0],
       [1.0, 0.0, 0.0, 1.0, 26.0, 106573.0],
       [0.0, 1.0, 0.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 20.0, 107675.0],
       [1.0, 0.0, 1.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 1.0, 0.0, 42.425, 84411.45],
       [0.0, 1.0, 0.0, 0.0, 42.425, 84411.45],
       [0.0, 1.0, 0.0, 0.0, 21.0, 88417.0],
       [1.0, 0.0, 0.0, 1.0, 41.0, 95610.0],
       [0.0, 1.0, 0.0, 0.0, 30.0, 93070.0],
       [0.0, 1.0, 0.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 42.0, 99195.0],
       [1.0, 0.0, 1.0, 0.0, 26.0, 72067.0],
       [0.0, 1.0, 0.0, 0.0, 57.0, 52503.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 111125.0],
       [1.0, 0.0, 0.0, 1.0, 68.0, 113726.0],
       [1.0, 0.0, 0.0, 1.0, 54.0, 67414.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 66479.0],
       [0.0, 1.0, 0.0, 0.0, 46.0, 43105.0],
       [1.0, 0.0, 0.0, 1.0, 42.425, 84411.45],
       [1.0, 0.0, 1.0, 0.0, 42.425, 84411.45],
       [1.0, 0.0, 0.0, 1.0, 58.0, 72774.0],
       

In [34]:
from sklearn.preprocessing import StandardScaler

In [36]:
ss = StandardScaler()
X = ss.fit_transform(X)

In [37]:
X

array([[-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.32252435,
        -0.03923179],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.19716666,
         1.03572262],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.        ,
         0.        ],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -1.63448781,
         1.08722472],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  0.        ,
         0.        ],
       [ 0.75      , -0.75      ,  1.77951304, -0.81649658,  0.        ,
         0.        ],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658,  0.        ,
         0.        ],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -1.56160095,
         0.18719985],
       [ 0.75      , -0.75      , -0.56195149,  1.22474487, -0.10386377,
         0.52336554],
       [-1.33333333,  1.33333333, -0.56195149, -0.81649658, -0.90561922,
         0.40465834],
       [-1.33333333,  1.33333333, -0.56195149, -0.